USE CASINO;

CREATE TABLE DEPARTMENT (
	DEP_ID INT PRIMARY KEY,
	DEP_NAME VARCHAR(39)
);

CREATE TABLE ROLE (
	ROLE_ID INT NOT NULL PRIMARY KEY,
	ROLE_TITLE VARCHAR(30) NOT NULL,
	ROLE_DESCRIPTION VARCHAR(75)
);

CREATE TABLE JOB_HIST (
	EMP_ID INT NOT NULL,
	DATE_ASSIGNED DATE NOT NULL,
	DEP_ID INT NOT NULL,
	ROLE_ID INT NOT NULL,
	EMP_PAY_RATE INT NOT NULL,
	FOREIGN KEY(EMP_ID) REFERENCES EMPLOYEE(EMP_ID),
	FOREIGN KEY(DEP_ID) REFERENCES DEPARTMENT(DEP_ID),
	FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ROLE_ID),
	PRIMARY KEY (EMP_ID, DATE_ASSIGNED, DEP_ID, ROLE_ID)
);

CREATE TABLE CERTIFICATION (
	CERT_ID INT NOT NULL PRIMARY KEY,
	CERT_NAME VARCHAR(30) NOT NULL,
	CERT_VALID_FOR DATE NOT NULL
);

CREATE TABLE ROLE_CERTIFICATION (
	CERT_ID INT NOT NULL,
	ROLE_ID INT NOT NULL,
	FOREIGN KEY(CERT_ID) REFERENCES CERTIFICATION(CERT_ID),
	FOREIGN KEY(ROLE_ID) REFERENCES ROLE(ROLE_ID),
	PRIMARY KEY(CERT_ID, ROLE_ID)
);
